apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-walk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-walk
  template:
    metadata:
      labels:
        app: smart-walk
    spec:
      containers:
      - name: smart-walk
        image: us-central1-docker.pkg.dev/qwiklabs-gcp-03-1051d07ccf83/smart-walk-repository/smart-walk:latest
        ports:
        - containerPort: 8080
        
